### ISSUE TITLE
returns null subtype err while getting getDetailsByPlaceId

### ISSUE THREAD

**Issue by wrteam02** [lejard-h/google_maps_webservice#143]
Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 7790): #0      _$PlacesDetailsResponseFromJson (package:google_maps_webservice/src/places.g.dart:294:50)
E/flutter ( 7790): #1      new PlacesDetailsResponse.fromJson (package:google_maps_webservice/src/places.dart:838:7)
E/flutter ( 7790): #2      GoogleMapsPlaces._decodeDetailsResponse (package:google_maps_webservice/src/places.dart:528:29)
E/flutter ( 7790): #3      GoogleMapsPlaces.getDetailsByPlaceId (package:google_maps_webservice/src/places.dart:126:12)

**Comment by casumatt** [comment]
An update on this item please. Here is the code (Flutter/Dart) causing the issues. If I remove the field mask it works fine.

```
PlacesDetailsResponse detail = await places.getDetailsByPlaceId(
            addressPlaceId,
            fields: ['places.location'],
          );
```
