### ISSUE TITLE
HandshakeException: Connection terminated during handshake 

### ISSUE THREAD

**Issue by lucasSzavara** [lejard-h/google_maps_webservice#49]
Hi, I'm using this package for autocomplete and it's working most of the time. But some users are reporting a HandshakeException. I don't have any ideas on how to reproduce it

The code:
```
final places = new GoogleMapsPlaces(apiKey: Global.instance.mapsKey)
locations = await places.autocomplete(
      text,
      types:  ['(regions)'],
      language: 'pt-br',
      components: [Component(Component.country, 'br')],
);
```
The Stack Trace (Using [catcher](https://github.com/jhomlala/catcher)):

```
#0 IOClient.send (package:http/src/io_client.dart:33)

#1 BaseClient._sendUnstreamed (package:http/src/base_client.dart:169)

#2 BaseClient.get (package:http/src/base_client.dart:32)
#3 GoogleWebService.doGet (package:google_maps_webservice/src/utils.dart:53)
#4 GoogleMapsPlaces.autocomplete (package:google_maps_webservice/src/places.dart:156)

#5 _LocalsState.filterByName (package:falta1/components/localsFilter.dart:141)

#6 EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:1003)
#7 EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:664)
#8 _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:728)

#9 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:383)

#10 MethodChannel.setMethodCallHandler. (package:flutter/src/services/platform_channel.dart:351)
#11 BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:73)

#12 _invoke3. (dart:ui/hooks.dart:253)
#13 _rootRun (dart:async/zone.dart:1124)
#14 _CustomZone.run (dart:async/zone.dart:1021)
#15 _CustomZone.runGuarded (dart:async/zone.dart:923)
#16 _invoke3 (dart:ui/hooks.dart:252)
#17 _dispatchPlatformMessage (dart:ui/hooks.dart:126)
```

Flutter doctor:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale
    en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/lucas/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18
      20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 28.0.3)
    • Android SDK at /home/lucas/Android/Sdk
    • Android NDK location not configured (optional; useful for
      native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at:
      /home/lucas/.local/share/JetBrains/Toolbox/apps/AndroidStudio/c
      h-0/183.5692245/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at
      /home/lucas/.local/share/JetBrains/Toolbox/apps/AndroidStudio/c
      h-0/183.5692245
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 •
      Android 8.1.0 (API 27) (emulator)

• No issues found!
```

Device Parameters (from [catcher](https://github.com/jhomlala/catcher)):
```
board: sdm660
bootloader: unknown
brand: xiaomi
device: lavender
display: PKQ1.180904.001
fingerprint: xiaomi/lavender/lavender:9/PKQ1.180904.001/V10.3.6.0.PFGMIXM:user/release-keys
hardware: qcom
host: mi-server
isPsychicalDevice: true
manufacturer: Xiaomi
model: Redmi Note 7
product: lavender
tags: release-keys
type: user
versionBaseOs:
versionCodename: REL
versionIncremental: V10.3.6.0.PFGMIXM
versionPreviewSdk: 0
versionRelase: 9
versionSdk: 28
versionSecurityPatch: 2019-05-05
```

**Comment by lejard-h** [comment]
Not sure this is related to the library. It seems to be a mobile network issue (Firewall ? ) or maybe from google server.
