### ISSUE TITLE
Error: FormatException: SyntaxError: Unexpected token S in JSON at position 0

### ISSUE THREAD

**Issue by hemanthkb97** [lejard-h/google_maps_webservice#92]
PlacesSearchResponse response =await places.searchByText("123 Main Street");

Restarted application in 414ms.
Error: FormatException: SyntaxError: Unexpected token S in JSON at position 0
    at Object.throw_ [as throw] (http://localhost:11311/dart_sdk.js:5342:11)
    at Object._parseJson (http://localhost:11311/dart_sdk.js:49743:19)
    at JsonDecoder.convert (http://localhost:11311/dart_sdk.js:47493:22)
    at JsonCodec.decode (http://localhost:11311/dart_sdk.js:47190:48)
    at places.GoogleMapsPlaces.new.[_decodeSearchResponse] (http://localhost:11311/packages/google_maps_webservice/src/places.dart.lib.js:339:76)
    at places.GoogleMapsPlaces.new.searchByText (http://localhost:11311/packages/google_maps_webservice/src/places.dart.lib.js:176:43)
    at searchByText.next (<anonymous>)
    at http://localhost:11311/dart_sdk.js:39157:33
    at _RootZone.runUnary (http://localhost:11311/dart_sdk.js:39014:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:11311/dart_sdk.js:34000:29)
    at handleValueCallback (http://localhost:11311/dart_sdk.js:34560:49)
    at Function._propagateToListeners (http://localhost:11311/dart_sdk.js:34598:17)
    at _Future.new.[_completeWithValue] (http://localhost:11311/dart_sdk.js:34440:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:11311/dart_sdk.js:34463:35)
    at Object._microtaskLoop (http://localhost:11311/dart_sdk.js:39301:13)
    at _startMicrotaskLoop (http://localhost:11311/dart_sdk.js:39307:13)
    at http://localhost:11311/dart_sdk.js:34814:9

**Comment by lejard-h** [comment]
Hello and thanks for report
can you add more context ? package version, dart sdk version, Flutter ?

**Comment by hemanthkb97** [comment]
> Hello and thanks for report
> can you add more context ? package version, dart sdk version, Flutter ?

Thank you for the help i fixed it  😊

**Comment by janoschpelzer** [comment]
@hemanthkb97  How did you fix it? I'm facing the same problem when running:   
```

final PlacesAutocompleteResponse placesAutocompleteResponse = await _googleMapsPlaces.autocomplete(
      pattern,
      location: Location(lat: 47.997791, lng: 7.842609),
      radius: 50,
      language: 'de',
      types: <String>['establishment'],
    );
```

**Comment by eqrakhattak** [comment]
> > Hello and thanks for report
> > can you add more context ? package version, dart sdk version, Flutter ?
> 
> Thank you for the help i fixed it 😊

@hemanthkb97 How did you fix it!? Saw #[87](https://github.com/lejard-h/google_maps_webservice/issues/87#issuecomment-725640974) but no solution.
Need help.

**Comment by sarbogast** [comment]
So, for those who are still looking for a solution, here is the one I found:
- I used the best answer in [this SO post](https://stackoverflow.com/questions/47076743/cors-anywhere-herokuapp-com-not-working-503-what-else-can-i-try/47085173#47085173) to deploy cors-anywhere to my heroku account
- Then I used the baseUrl argument to go through the proxy on heroku:

```
    final places = new googlePlaces.GoogleMapsPlaces(
        apiKey: googlePlacesApiKey,
        baseUrl: kIsWeb
            ? 'https://[heroku app name].herokuapp.com/https://maps.googleapis.com/maps/api'
            : null,
      );
```
You shouldn't use https://cors-anywhere.herokuapp.com as a proxy because it is a test set up, not meant to be used in real applications. I suspect that's why this proxy gets a FormatException.
